### ISSUE TITLE
What is the max count number

### ISSUE THREAD

**Issue by seiflotfy** [bitly/dablooms#67]
What is the max count in the scalable bloom filter

**Comment by ploxiln** [comment]
Do you mean, the maximum number of times the same key can be added?

The counters are 4 bits, so they can count from 0 up to 15. But there are collisions of individual bits in a bloom filter (which is what allows it to "record" the fingerprint of more keys than a hash table in the same amount of space). So I'd suggest not adding more than 2 or 3 of the exact same key.

So, it's not really useful for adding multiple of the same key. You should probably make sure you only add one of a particular key, by checking before adding. The counting is only sufficient to allow you to remove a key, even with the inevitable collisions of some bits. The bins count up enough that if you're getting enough collisions to overflow some counts from *unique* keys, the bloom filter is way too full already, the scalable bloom filter would have already started on a new bloom.

Also, this repo isn't really maintained anymore, fwiw :)
